### ISSUE TITLE
architecture question

### ISSUE THREAD

**Issue by seblemaguer** [AndroidMaryTTS/AndroidMaryTTS#2]
Hello,

why have the marytts source code inside the repository ? Did you have modify something inside it ? If yes, we should proceed a little bit differently.

**Comment by farizaghayev** [comment]
@seblemaguer We have done significant refactoring and modifications in the the core code MaryTTS : 

Refactor java maven project structure to one single android module
Enable all java audio package for android module
Enable all java.beans package for android module 
Refactoring freetts and jtok projects for android module 
Create TTS engine with using AndroidMaryTTS
Use xerces for Android XML parser
Using other android technologies: AsyncTask, Handler,  Service, AIDL, etc ...
Etc...

**Comment by seblemaguer** [comment]
ok, do you remember from which commit and which branch ?

**Comment by amirashad** [comment]
@psibre @seblemaguer, I remember that we started with taking the latest release version [MaryTTS 5.1.2](https://github.com/marytts/marytts/tree/v5.1.2).

**Comment by seblemaguer** [comment]
I see but the problem is you have merged all the files in one marytts subdirectory instead of keeping the marytts architecture.  Therefore it starts to be complicated to monitor your changes and include them in the original repository. Was there a specific reason for that ?

**Comment by amirashad** [comment]
The reason of changing marytts architecture:
Maven projects supports [Acyclic dependencies principle] (https://en.wikipedia.org/wiki/Acyclic_dependencies_principle). But libs marytts-builder and marytts-runtime modules depend on each other and it's impossible to keep this architecture in android platform.

We are open to your suggestions.

**Comment by psibre** [comment]
I agree that the various modules are somewhat convoluted, but `marytts-runtime` does *not* depend on `marytts-builder` -- that would lead to a cyclical dependency in Maven. What's more, even if that were somehow the case, you could easily override such transitive dependencies in Gradle.
I'm afraid I don't follow your arguments at all.

**Comment by farizaghayev** [comment]
![mary](https://cloud.githubusercontent.com/assets/18733219/18393083/2bc8bb22-76c5-11e6-8ad2-512d8239f233.png)

**Comment by farizaghayev** [comment]
@psibre  @seblemaguer  @amirashad  You are right that there is not direct dependence between these modules but I remember that because of acyclical dependency we destroy marytts architecture. We have already started to refactor our code with keeping marytts architecture and finished it until end of next week.  

Thanks your suggestion and we are always open to your suggestions.

**Comment by seblemaguer** [comment]
my point is that basically we can see to integrate what you need directly in marytts and therefore make your repository clearer and more robust :)

**Comment by amirashad** [comment]
@seblemaguer  @psibre  @farizaghayev 
For android app we need `marytts-common`, `marytts-runtime`, `marytts-signalproc`, `voice-cmu-slt-hsmm`, `marytts-languages` modules.

But in these modules exists some classes which are not supperted by Android. For example:
1) Swing, AWT GUI components, such as JFrame, JPanel, ...
2) Java Audio Classes, such as (AudioSystem, AudioInputStream, etc) inside javax.sound package. 
3) Some Java Beans Classes not exists in Android.
4) NIO Classes. Some classes missing in android NIO package.
6) javax package classes are not full implemented for android.  such as DocumentBuilderFactory, Xml parser etc.
7) We use gradle, but you maven.
8) etc ...



How can we merge to and upgrade from original repository with keeping marytts architecture? We are waiting for your suggestions.

To solve all these problems, we can make a audio/video conversation. Our purpose is to fix all these problems after your agreements.

**Comment by psibre** [comment]
Some things will be stripped out for MaryTTS 6, in particular the Swing and AWT stuff (which is only there for the InstallerGUI), and the XML handling. Moreover, we will switch from Maven to Gradle. So I would suggest you wait for the first alpha of v6 or follow `upstream/master` in the coming weeks. =)

**Comment by amirashad** [comment]
Great. We also can help and contribute for relevant changings.
