### ISSUE TITLE
Adding new language support by importing model from MaryTTS

### ISSUE THREAD

**Issue by kantajit** [AndroidMaryTTS/AndroidMaryTTS#3]
We have a MaryTTS server for a regional language running fine on desktop.
We would like to extend AndroidMaryTTS to support that language. We tried replacing the model files in assets directory of the Android Project (marylib/src/main/assets/marytts/voice/CmuSltHsmm). We are getting this error

```
11-21 15:06:18.216 1830-2060/marytts.android D/test: Cannot instantiate model 'duration' of type 'hmm' from 'null'
11-21 15:06:18.219 1830-2060/marytts.android D/test: 2 Cannot instantiate voice 'cmu-slt-hsmm' Cannot instantiate model 'duration' of type 'hmm' from 'null'
11-21 15:06:18.219 1830-2060/marytts.android D/test: java.lang.Exception: Problem starting module marytts.modules.Synthesis@995928f
11-21 15:06:18.219 1830-2060/marytts.android D/test: marytts.exceptions.MaryConfigurationException: Cannot start MARY server
```
Kindly let us know whether it will work or not.

**Comment by farizaghayev** [comment]
Thanks for interest in this repo. Actually our lib don't support to add new language. But we can help you to implement it in your language. Therefore we need your language and voice model.  Share with us and we will implement for you. @kantajit
