### ISSUE TITLE
Changing voice

### ISSUE THREAD

**Issue by Cesarsk** [AndroidMaryTTS/AndroidMaryTTS#5]
Is it possible to change and tune the voices? I can't figure it out how.

**Comment by farizaghayev** [comment]
Until end of this or next week i will add audio effect, pitch and tune the voice as  DEMO website. As input format can take RAWMARYXML and change **rate** parameter or add new one in **MaryLink** class.

[MaryLink](https://github.com/AndroidMaryTTS/AndroidMaryTTS/blob/master/marylib/src/main/java/com/marytts/android/link/MaryLink.java)
